source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '12.0'
inhibit_all_warnings!

target 'SpeechmaticsDemo' do

pod 'AgoraRtcEngine_iOS', '~> 4.1.1'
pod 'Starscream'
pod 'Alamofire'
pod 'MBProgressHUD'

end
